# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 03:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('DateOfBirth', models.DateTimeField(verbose_name='birth date')),
                ('Address', models.CharField(max_length=300)),
                ('Nationality', models.CharField(max_length=100)),
                ('UniqueID', models.CharField(max_length=50)),
                ('IDType', models.IntegerField(default=0)),
                ('TestID', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TestResult', models.IntegerField(default=0)),
                ('TestData', models.CharField(max_length=2000)),
                ('TestID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testreg.Applicant')),
            ],
        ),
    ]
