# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testreg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='Sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='IDType',
            field=models.CharField(choices=[('A', 'Aadhaar'), ('P', 'PAN')], max_length=1),
        ),
    ]
