# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 19:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import testreg.models


class Migration(migrations.Migration):

    dependencies = [
        ('testreg', '0003_auto_20160709_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='TestData',
            field=models.FileField(default=datetime.datetime(2016, 7, 9, 19, 45, 51, 764831, tzinfo=utc), upload_to=testreg.models.user_directory_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='test',
            name='TestDate',
            field=models.DateTimeField(verbose_name='Test date'),
        ),
    ]
