# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testreg', '0004_auto_20160709_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='TestResult',
            field=models.CharField(choices=[('P', 'PASS'), ('F', 'FAIL'), ('C', 'CANCELLED')], max_length=1),
        ),
    ]
