/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package autodrivetest;

/**
 *
 * @author SPoojary
 */
public class DriveLayout extends javax.swing.JFrame {

    /**
     * Creates new form DriveLayout
     */
    public DriveLayout() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Track = new javax.swing.JPanel();
        testTrack = new autodrivetest.TestTrack();
        VehicleControl = new javax.swing.JPanel();
        down = new javax.swing.JButton();
        left = new javax.swing.JButton();
        right = new javax.swing.JButton();
        stop = new javax.swing.JButton();
        up = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Track.setBackground(new java.awt.Color(0, 102, 51));
        Track.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 102, 102)));
        Track.setForeground(new java.awt.Color(51, 51, 0));
        Track.setPreferredSize(new java.awt.Dimension(600, 600));

        testTrack.setBackground(new java.awt.Color(153, 153, 0));
        testTrack.setPreferredSize(new java.awt.Dimension(500, 500));

        javax.swing.GroupLayout testTrackLayout = new javax.swing.GroupLayout(testTrack);
        testTrack.setLayout(testTrackLayout);
        testTrackLayout.setHorizontalGroup(
            testTrackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );
        testTrackLayout.setVerticalGroup(
            testTrackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout TrackLayout = new javax.swing.GroupLayout(Track);
        Track.setLayout(TrackLayout);
        TrackLayout.setHorizontalGroup(
            TrackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TrackLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(testTrack, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                .addContainerGap())
        );
        TrackLayout.setVerticalGroup(
            TrackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TrackLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(testTrack, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                .addContainerGap())
        );

        VehicleControl.setBackground(new java.awt.Color(153, 153, 0));
        VehicleControl.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 102, 102)));

        down.setBackground(new java.awt.Color(255, 204, 51));
        down.setText("DN");
        down.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downActionPerformed(evt);
            }
        });

        left.setBackground(new java.awt.Color(51, 255, 0));
        left.setText("LT");
        left.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftActionPerformed(evt);
            }
        });

        right.setBackground(new java.awt.Color(51, 255, 0));
        right.setText("RT");
        right.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightActionPerformed(evt);
            }
        });

        stop.setBackground(new java.awt.Color(255, 0, 51));
        stop.setText("ST");

        up.setBackground(new java.awt.Color(51, 255, 0));
        up.setText("UP");
        up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout VehicleControlLayout = new javax.swing.GroupLayout(VehicleControl);
        VehicleControl.setLayout(VehicleControlLayout);
        VehicleControlLayout.setHorizontalGroup(
            VehicleControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VehicleControlLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(left)
                .addGap(18, 18, 18)
                .addGroup(VehicleControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(up)
                    .addComponent(down)
                    .addGroup(VehicleControlLayout.createSequentialGroup()
                        .addComponent(stop)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(right))))
        );
        VehicleControlLayout.setVerticalGroup(
            VehicleControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VehicleControlLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(up)
                .addGap(18, 18, 18)
                .addGroup(VehicleControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(left)
                    .addComponent(right)
                    .addComponent(stop))
                .addGap(18, 18, 18)
                .addComponent(down)
                .addContainerGap(247, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Track, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(VehicleControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Track, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
            .addComponent(VehicleControl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void downActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downActionPerformed
        System.out.println("Car going reverse");
        testTrack.moveCarBack();
        testTrack.paintComponent(testTrack.getGraphics());
    }//GEN-LAST:event_downActionPerformed

    private void leftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftActionPerformed
        System.out.println("Car going left");
        testTrack.moveCarLeft();
        testTrack.paintComponent(testTrack.getGraphics());
    }//GEN-LAST:event_leftActionPerformed

    private void rightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightActionPerformed
        System.out.println("Car going right");
        testTrack.moveCarRight();
        testTrack.paintComponent(testTrack.getGraphics());
    }//GEN-LAST:event_rightActionPerformed

    private void upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upActionPerformed
        testTrack.moveCarUp();
        //testTrack.revalidate();
        testTrack.paintComponent(testTrack.getGraphics());
        //testTrack.moveCar(testTrack.getGraphics());
    }//GEN-LAST:event_upActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Track;
    private javax.swing.JPanel VehicleControl;
    private javax.swing.JButton down;
    private javax.swing.JButton left;
    private javax.swing.JButton right;
    private javax.swing.JButton stop;
    private autodrivetest.TestTrack testTrack;
    private javax.swing.JButton up;
    // End of variables declaration//GEN-END:variables
}
